"""
Router: /api/v1/persona
Repo profiling and auto-generated onboarding guide generation.

Phase 3 — Week 7 implementation.
"""

from fastapi import APIRouter, HTTPException
from app.models.schemas import PersonaRequest, PersonaResponse

router = APIRouter()


@router.post("/", response_model=PersonaResponse, summary="Generate repo persona")
async def generate_persona(request: PersonaRequest):
    """
    Analyze the ingested repo and generate:
      - Repo Identity Card: dominant language, frameworks, conventions, key contributors
      - Architecture overview: text-based diagram of the folder structure + module relationships
      - Onboarding guide: step-by-step "Getting Started" doc (markdown) generated by LLM
        using the README, folder structure, and key file summaries as context
    """
    # TODO: Implement in Phase 3 - Week 7
    raise HTTPException(status_code=501, detail="Not implemented yet — Phase 3 Week 7")


@router.get("/{repo_id}", summary="Get cached repo persona")
async def get_persona(repo_id: str):
    """
    Return the previously generated persona for a repo (cached in DB).
    """
    # TODO: Implement in Phase 3 - Week 7
    raise HTTPException(status_code=501, detail="Not implemented yet — Phase 3 Week 7")
